### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by dr-peterson** [Josepdal/DBTeam#104]
Hello mr. why tmux is run on my session but if bot crashed, tmux is runing and show BOT RUNING! but Bot is Crashed and dont receipt msg !! how can fix this problem ?
my bot is cloned by your github and i dont think need to change steady.sh information so why bot is dont receive massage while tmux is runing !!

**Comment by iicc1** [comment]
Does the bot run if you launch it as the normal way? 
`./launch.sh`

**Comment by dr-peterson** [comment]
yes but run

**Comment by dr-peterson** [comment]
any Ideas ? :confused:

**Comment by Josepdal** [comment]
There are a bug in some supergroups, have to be that...

**Comment by iicc1** [comment]
Have you checked if works in normal groups?

**Comment by dr-peterson** [comment]
@iicc1 Difference does it make? tmux can understanding this is normal groups or supergroups:confused:

**Comment by dr-peterson** [comment]
if tmux  runed so must re./launch.sh Bot What difference had does this is groups or supergroups !!

**Comment by Josepdal** [comment]
@dr-peterson https://github.com/vysheng/tg/issues/1067

**Comment by dr-peterson** [comment]
Tell me what to do !

**Comment by Josepdal** [comment]
@dr-peterson hold on

**Comment by BH-YAGHI** [comment]
@dr-peterson  Perhaps the problem is the disconnection and connection vps.

**Comment by dr-peterson** [comment]
ok

**Comment by dr-peterson** [comment]
@iicc1 can Write or Editing This Script with dont problem or bug!! ?

**Comment by iicc1** [comment]
The problem must be telegram-cli or vps related. If not, error messages would show in the script
