### ISSUE TITLE
config.lua is empty

### ISSUE THREAD

**Issue by toaskoas** [Josepdal/DBTeam#106]
i can not add my id as sudo.

**Comment by Josepdal** [comment]
We are working on it :+1:

**Comment by iicc1** [comment]
Solved in https://github.com/Josepdal/DBTeam/commit/e75a9be00c519c06fca3156f5e4f1a910c95d931 and https://github.com/Josepdal/DBTeam/commit/d5712c7e9a9bba7f7586289c11dc2858ee6fa6d6
Thanks for the feedback :+1:
