### ISSUE TITLE
Not working in open supergroups

### ISSUE THREAD

**Issue by toaskoas** [Josepdal/DBTeam#111]

**Comment by Josepdal** [comment]
![Novedad](http://www.fallascervera.com/novedad.gif)

**Comment by Josepdal** [comment]
That's a tg-cli problem

**Comment by BH-YAGHI** [comment]
[see this](https://github.com/Josepdal/tg/pull/5) @Josepdal

**Comment by BH-YAGHI** [comment]
کس میتی بقران @Josepdal  :octocat:

**Comment by Josepdal** [comment]
That will not solve that problem. Problem in this 5k supergroups is the way that telegram servers notify tg-cli bot. 
Bot has to receive a push from telegram servers, like old groups or push by himself to telegram servers to know if there are new messages to read. And those are the unique solutions...

**Comment by BH-YAGHI** [comment]
@Josepdal  anyway this is problem. you most edite {lua-tg.c} to 5000 members.
