### ISSUE TITLE
bug !

### ISSUE THREAD

**Issue by BH-YAGHI** [Josepdal/DBTeam#135]
![image](https://cloud.githubusercontent.com/assets/17055732/14763113/73ca9aa8-09a1-11e6-93e7-d85bde275ae3.png)

fix that...

**Comment by BH-YAGHI** [comment]
Error loading language arabic_lang                                                                                                                         
lua: lang/arabic_lang.lua:48: unexpected symbol near ')'                                                                                                   
                                                                                                                                                           
./bot/bot.lua:319: attempt to call a nil value

**Comment by Josepdal** [comment]
git pull :+1:
