### ISSUE TITLE
qustion

### ISSUE THREAD

**Issue by BH-YAGHI** [Josepdal/DBTeam#140]
@iicc1  Boy If VPS is Rebooted steady.sh can Re launch Bot ?? 
I want Write reboot with steady.sh but i want know this script can be Re launch Bot after reboot ??
this is not creazy Ideas i want Write reboot vps at 6:00 Morning :)
all people is sleeped its good for Refresh Vps :ghost: 
so say me Boy If VPS is Rebooted steady.sh can Re launch Bot or not! 
thank you!

**Comment by Josepdal** [comment]
The only thing i'm gonna say is, daily reboot for what?

**Comment by iicc1** [comment]
I believe that you can do this putting this at the beginning of steady.sh
`echo '"tmux new-session -d -s script "bash steady.sh -t"' | at 06:00`

This will start steady.sh with tmux detached every day at 6:00

**Comment by BH-YAGHI** [comment]
Nice

**Comment by BH-YAGHI** [comment]
### boy Which lines most Add this echo ???

echo '"tmux new-session -d -s script "bash steady.sh -t"' | at 06:00

**Comment by BH-YAGHI** [comment]
# reload steady after 10h
	if [ "$OK" == 2400 ]; then
		sync
		sudo sh -c echo '"tmux new-session -d -s script "bash steady.sh -t"'
	fi




this is false ?
