### ISSUE TITLE
 lua: ./bot/bot.lua:120: bad argument #1 to 'pairs' (table expected, got nil)

### ISSUE THREAD

**Issue by toaskoas** [Josepdal/DBTeam#142]
the bot is not working

**Comment by Josepdal** [comment]
Reinstall it from 0, you changed something wrong and we cannot review all your code...

**Comment by toaskoas** [comment]
i install it with your instruction here. i add me and my second account as sudo. i gave the bot, the phonenumber from the second account. thats all

**Comment by Josepdal** [comment]
`-- Apply plugin.pre_process function
function pre_process_msg(msg)
  for name,plugin in pairs(plugins) do
    if plugin.pre_process and msg then
      print('Preprocess', name)
      msg = plugin.pre_process(msg)
    end
  end`

**Comment by toaskoas** [comment]
i dont now what do you mean. where should i paste this in?

**Comment by BH-YAGHI** [comment]
paste this all [CODE](https://github.com/Josepdal/DBTeam/blob/master/bot/bot.lua) to yout bot.lua file

Do not forgot change sudo ID to Line 259 
sudo_users = {add here your ID},

this error maybe for add wrong sudo ID
