### ISSUE TITLE
module 'serpent' not found:

### ISSUE THREAD

**Issue by ghost** [Josepdal/DBTeam#19]
** 1456740639.528893 lua: .///bot/utils.lua:5: module 'serpent' not found:
        no field package.preload['serpent']
        no file '/usr/local/share/lua/5.2/serpent.lua'
        no file '/usr/local/share/lua/5.2/serpent/init.lua'
        no file '/usr/local/lib/lua/5.2/serpent.lua'
        no file '/usr/local/lib/lua/5.2/serpent/init.lua'
        no file '/usr/share/lua/5.2/serpent.lua'
        no file '/usr/share/lua/5.2/serpent/init.lua'
        no file './serpent.lua'
        no file '.luarocks/share/lua/5.2/serpent.lua'
        no file '.luarocks/share/lua/5.2/serpent/init.lua'
        no file '/usr/local/lib/lua/5.2/serpent.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.2/serpent.so'
        no file '/usr/lib/lua/5.2/serpent.so'
        no file '/usr/local/lib/lua/5.2/loadall.so'
        no file './serpent.so'
        no file '.luarocks/lib/lua/5.2/serpent.so'

**Comment by iicc1** [comment]
`sudo luarocks install serpent`

**Comment by jack-peterson** [comment]
how  time ??
i waiting 8 hurs but .....

**Comment by Josepdal** [comment]
Reinstall it from 0, try to use one command installed
