### ISSUE TITLE
#FIX MUTE ALL

### ISSUE THREAD

**Issue by BH-YAGHI** [Josepdal/DBTeam#28]
Fix muta all languange . if we enable/diable this plugin, but dont send mute all command. i think U dont add mute all to ENGLISH_lang

**Comment by Josepdal** [comment]
Maybe you have to update your bot and translations...

**Comment by jack-peterson1** [comment]
its nod work  check it !

**Comment by amir-sereen** [comment]
#muteall ?? its working fine

**Comment by Josepdal** [comment]
Commands are:
#muteall
#muteall [secs]
#unmuteall

You have to update your bot up to last version to do that...
