### ISSUE TITLE
#BOT HAVE 2 PROBLEM

### ISSUE THREAD

**Issue by BH-YAGHI** [Josepdal/DBTeam#33]
1- BOT Crashing for 5 min after ./launch.sh
----------------------------
 *** 1456859482.006978 lua: attempt to call a nil value                                       
> *** Error in `./tg/bin/telegram-cli': double free or corruption (fasttop): 0x000000000e59033
0 ***
SIGNAL received
h./tg/bin/telegram-cli(print_backtrace+0x20)[0x46edb0]
./tg/bin/telegram-cli(termination_signal_handler+0x64)[0x46ee34]
/lib/x86_64-linux-gnu/libc.so.6(+0x36d40)[0x7f0106599d40]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x39)[0x7f0106599cc9]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x148)[0x7f010659d0d8]
/lib/x86_64-linux-gnu/libc.so.6(+0x73394)[0x7f01065d6394]
/lib/x86_64-linux-gnu/libc.so.6(+0x7f66e)[0x7f01065e266e]
./tg/bin/telegram-cli[0x4929ff]
./tg/bin/telegram-cli(tglq_query_result+0x10f)[0x4986ef]
./tg/bin/telegram-cli[0x490fda]
./tg/bin/telegram-cli[0x4b64fb]
/usr/lib/x86_64-linux-gnu/libevent-2.0.so.5(event_base_loop+0x754)[0x7f01079d6f24]
./tg/bin/telegram-cli(net_loop+0xa6)[0x470336]
./tg/bin/telegram-cli(loop+0x187)[0x471637]
./tg/bin/telegram-cli(main+0x2e5)[0x46d615]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f0106584ec5]
./tg/bin/telegram-cli[0x46d725]
root@localhost:~/py#  
------------------------------------------------------------------------------------------------------------
2- If Admin Mute Sodu in Group So sudo is muting !!!!!!!!!!!!!!!!!!!!!!!!!!1
its so big problem...

**Comment by Josepdal** [comment]
1. Are you using c9?
2. Will be fixed this night :smiley:

**Comment by BH-YAGHI** [comment]
no i use KOding, My VPS is connect To Koding site. but It has nothing to do with c9 or other vps

	},
	crash= crash
![image](https://cloud.githubusercontent.com/assets/17055732/13440024/010c0b7e-dfe8-11e5-9d92-95c469e68533.png)

}
