### ISSUE TITLE
spam.lua -- no username means --> no report

### ISSUE THREAD

**Issue by pnmvhd** [Josepdal/DBTeam#43]
in one of the SuperGroups

Preprocess      bot
Preprocess      settings
Preprocess      moderation
 *** 1458145079.589744 lua: plugins/moderation.lua:399: bad argument #1 to 'len' (string expected, got nil)

:-/
commented these codes and problem gone XD
      --  hash = 'antibot:'..msg.to.id
       -- if redis:get(hash) then
       --     if string.sub(msg.from.username, (string.len(msg.from.username)-2), string.len(msg.from.username)) == 'bot' then
       --         kick_user(user_id, chat_id)
       --     end
       -- end

and

Preprocess      bot
Preprocess      settings
Preprocess      moderation
Preprocess      stats
Saving user     user:xxxxxxxxx
msg matches: [Tt][Ee][Ll][Ee][Gg][Rr][Aa][Mm]%.[Mm][Ee]
 *** 1458125662.060747 lua: plugins/spam.lua:15: attempt to concatenate field
# **'username' (a nil value)**

# Use _```or```_ in between

# the one i made correct is attached below and cause github does not support lua, I added ```txt``` extension
# attachment
[spam.lua.txt](https://github.com/Josepdal/DBTeam/files/175944/spam.lua.txt)

**Comment by pnmvhd** [comment]
hash = 'antibot:'..msg.to.id
        if redis:get(hash) then
            if string.sub(msg.from.username or '', (string.len(msg.from.username or '')-2), string.len(msg.from.username or '')) == 'bot' then
                kick_user(user_id, chat_id)
            end
        end
    end
    return msg
end

using new spam.lua
changed the code to this

**Comment by Josepdal** [comment]
@pnmvhd OOO!

**Comment by Josepdal** [comment]
Ops thats bacause user can exist without username. So I have to check it before using an inexistent name... Thanks for your report! Will update it as soon as I can.

**Comment by pnmvhd** [comment]
i gave the spam.lua with the problem fixed

whats the first problem then ??

**Comment by Josepdal** [comment]
The same, not?

**Comment by pnmvhd** [comment]
in one of the SuperGroups

Preprocess bot
Preprocess settings
Preprocess moderation
*** 1458145079.589744 lua: plugins/moderation.lua:399: bad argument #1 to 'len' (string expected, got nil)

i made it correct
but
i wanna know what is it for ?

**Comment by iicc1** [comment]
It checks in the username the word "bot", it is the antibot.

**Comment by pnmvhd** [comment]
why is it giving this only in that specific group ?

**Comment by Josepdal** [comment]
@pnmvhd Because in that group there is a member without username.

**Comment by pnmvhd** [comment]
uh thx :)
